//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AresToys.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AresToys.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-switch to JPEG when output exceeds threshold.
        /// </summary>
        public static string Capture_AutoJpeg {
            get {
                return ResourceManager.GetString("Capture_AutoJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active only when format = PNG. Photographic content (gradients, video stills) compresses far more efficiently as JPEG; large screenshots fall back automatically without you noticing..
        /// </summary>
        public static string Capture_AutoJpegHint {
            get {
                return ResourceManager.GetString("Capture_AutoJpegHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults applied when triggering captures from the tray menu or hotkeys. The pipeline that runs after each capture is configured under Workflows..
        /// </summary>
        public static string Capture_Blurb {
            get {
                return ResourceManager.GetString("Capture_Blurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot delay (seconds).
        /// </summary>
        public static string Capture_DelaySeconds {
            get {
                return ResourceManager.GetString("Capture_DelaySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External text editor.
        /// </summary>
        public static string Capture_ExternalEditor {
            get {
                return ResourceManager.GetString("Capture_ExternalEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used by the clipboard popup&apos;s Edit button on text rows. Examples: code (VSCode), code.cmd, notepad++.exe, notepad. Edits sync back automatically when you save the file..
        /// </summary>
        public static string Capture_ExternalEditorHint {
            get {
                return ResourceManager.GetString("Capture_ExternalEditorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (empty = Windows default for .txt — e.g. notepad).
        /// </summary>
        public static string Capture_ExternalEditorPlaceholder {
            get {
                return ResourceManager.GetString("Capture_ExternalEditorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image format.
        /// </summary>
        public static string Capture_ImageFormat {
            get {
                return ResourceManager.GetString("Capture_ImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG quality.
        /// </summary>
        public static string Capture_JpegQuality {
            get {
                return ResourceManager.GetString("Capture_JpegQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save folder.
        /// </summary>
        public static string Capture_SaveFolder {
            get {
                return ResourceManager.GetString("Capture_SaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens: %y / %yy 4-digit / 2-digit year, %mo month (01–12), %mon month name, %d day, %h hour, %mi minute, %s second, %pm AM/PM. Leave empty for no sub-folder..
        /// </summary>
        public static string Capture_SubFolderHint {
            get {
                return ResourceManager.GetString("Capture_SubFolderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-folder pattern (optional).
        /// </summary>
        public static string Capture_SubFolderPattern {
            get {
                return ResourceManager.GetString("Capture_SubFolderPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. %y-%mo  →  2026-04 sub-folder under the save folder.
        /// </summary>
        public static string Capture_SubFolderPlaceholder {
            get {
                return ResourceManager.GetString("Capture_SubFolderPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold (KB).
        /// </summary>
        public static string Capture_ThresholdKb {
            get {
                return ResourceManager.GetString("Capture_ThresholdKb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new category.
        /// </summary>
        public static string Categories_AddNew {
            get {
                return ResourceManager.GetString("Categories_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories are buckets for clipboard items. Right-click any item in the popup → Move to → … to file it. Items in deleted categories return to the default &apos;Clipboard&apos; bucket; pinned items keep their pin..
        /// </summary>
        public static string Categories_Blurb {
            get {
                return ResourceManager.GetString("Categories_Blurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (e.g. Code).
        /// </summary>
        public static string Categories_NewNamePlaceholder {
            get {
                return ResourceManager.GetString("Categories_NewNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to.
        /// </summary>
        public static string Clipboard_MenuCopyTo {
            get {
                return ResourceManager.GetString("Clipboard_MenuCopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate QR code….
        /// </summary>
        public static string Clipboard_MenuGenerateQr {
            get {
                return ResourceManager.GetString("Clipboard_MenuGenerateQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to.
        /// </summary>
        public static string Clipboard_MenuMoveTo {
            get {
                return ResourceManager.GetString("Clipboard_MenuMoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin / unpin.
        /// </summary>
        public static string Clipboard_MenuPinUnpin {
            get {
                return ResourceManager.GetString("Clipboard_MenuPinUnpin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rename label (F2).
        /// </summary>
        public static string Clipboard_MenuRenameLabel {
            get {
                return ResourceManager.GetString("Clipboard_MenuRenameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a label….
        /// </summary>
        public static string Clipboard_LabelPlaceholder {
            get {
                return ResourceManager.GetString("Clipboard_LabelPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move up in pinned order.
        /// </summary>
        public static string Clipboard_TooltipMoveUp {
            get {
                return ResourceManager.GetString("Clipboard_TooltipMoveUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move down in pinned order.
        /// </summary>
        public static string Clipboard_TooltipMoveDown {
            get {
                return ResourceManager.GetString("Clipboard_TooltipMoveDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string Settings_ClipboardSectionTitle {
            get {
                return ResourceManager.GetString("Settings_ClipboardSectionTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display options for the clipboard window..
        /// </summary>
        public static string Settings_ClipboardSectionHint {
            get {
                return ResourceManager.GetString("Settings_ClipboardSectionHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show content snippet under label.
        /// </summary>
        public static string Settings_ClipboardShowSnippetWithLabel {
            get {
                return ResourceManager.GetString("Settings_ClipboardShowSnippetWithLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When an item has a label, also render a small preview of its content on a second line. Off by default — the label replaces the snippet entirely..
        /// </summary>
        public static string Settings_ClipboardShowSnippetWithLabelTooltip {
            get {
                return ResourceManager.GetString("Settings_ClipboardShowSnippetWithLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍 Search….
        /// </summary>
        public static string Clipboard_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Clipboard_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AresToys - Clipboard.
        /// </summary>
        public static string Clipboard_Title {
            get {
                return ResourceManager.GetString("Clipboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture webpage (full-page screenshot of the URL).
        /// </summary>
        public static string Clipboard_TooltipCaptureWebpage {
            get {
                return ResourceManager.GetString("Clipboard_TooltipCaptureWebpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete every non-pinned item (Ctrl+Shift+Del).
        /// </summary>
        public static string Clipboard_TooltipClearAll {
            get {
                return ResourceManager.GetString("Clipboard_TooltipClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete (Del).
        /// </summary>
        public static string Clipboard_TooltipDelete {
            get {
                return ResourceManager.GetString("Clipboard_TooltipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit text in external editor (VSCode / Notepad / …).
        /// </summary>
        public static string Clipboard_TooltipExtEditor {
            get {
                return ResourceManager.GetString("Clipboard_TooltipExtEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in image editor.
        /// </summary>
        public static string Clipboard_TooltipOpenEditor {
            get {
                return ResourceManager.GetString("Clipboard_TooltipOpenEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open URL in browser.
        /// </summary>
        public static string Clipboard_TooltipOpenUrl {
            get {
                return ResourceManager.GetString("Clipboard_TooltipOpenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (Enter).
        /// </summary>
        public static string Clipboard_TooltipPaste {
            get {
                return ResourceManager.GetString("Clipboard_TooltipPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin / unpin (Ctrl+P).
        /// </summary>
        public static string Clipboard_TooltipPin {
            get {
                return ResourceManager.GetString("Clipboard_TooltipPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle pinned (sticky) mode — popup stays open after paste / double-click. Esc or Win+V still dismiss..
        /// </summary>
        public static string Clipboard_TooltipPinned {
            get {
                return ResourceManager.GetString("Clipboard_TooltipPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate QR code….
        /// </summary>
        public static string Clipboard_TooltipQr {
            get {
                return ResourceManager.GetString("Clipboard_TooltipQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in explorer.
        /// </summary>
        public static string Clipboard_TooltipShowExplorer {
            get {
                return ResourceManager.GetString("Clipboard_TooltipShowExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all.
        /// </summary>
        public static string ColorPicker_CopyAll {
            get {
                return ResourceManager.GetString("ColorPicker_CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy BGRA.
        /// </summary>
        public static string ColorPicker_CopyBgra {
            get {
                return ResourceManager.GetString("ColorPicker_CopyBgra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy CMYK.
        /// </summary>
        public static string ColorPicker_CopyCmyk {
            get {
                return ResourceManager.GetString("ColorPicker_CopyCmyk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 DEC.
        /// </summary>
        public static string ColorPicker_CopyDec {
            get {
                return ResourceManager.GetString("ColorPicker_CopyDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 HEX.
        /// </summary>
        public static string ColorPicker_CopyHex {
            get {
                return ResourceManager.GetString("ColorPicker_CopyHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy HSB.
        /// </summary>
        public static string ColorPicker_CopyHsb {
            get {
                return ResourceManager.GetString("ColorPicker_CopyHsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Linear.
        /// </summary>
        public static string ColorPicker_CopyLinear {
            get {
                return ResourceManager.GetString("ColorPicker_CopyLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy RGB.
        /// </summary>
        public static string ColorPicker_CopyRgb {
            get {
                return ResourceManager.GetString("ColorPicker_CopyRgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string ColorPicker_Recent {
            get {
                return ResourceManager.GetString("ColorPicker_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampler.
        /// </summary>
        public static string ColorPicker_Sampler {
            get {
                return ResourceManager.GetString("ColorPicker_Sampler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string ColorPicker_Square {
            get {
                return ResourceManager.GetString("ColorPicker_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AresToys - Color picker.
        /// </summary>
        public static string ColorPicker_Title {
            get {
                return ResourceManager.GetString("ColorPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel.
        /// </summary>
        public static string ColorPicker_Wheel {
            get {
                return ResourceManager.GetString("ColorPicker_Wheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Common_Apply {
            get {
                return ResourceManager.GetString("Common_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse….
        /// </summary>
        public static string Common_Browse {
            get {
                return ResourceManager.GetString("Common_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure….
        /// </summary>
        public static string Common_Configure {
            get {
                return ResourceManager.GetString("Common_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Common_Copy {
            get {
                return ResourceManager.GetString("Common_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Common_Duplicate {
            get {
                return ResourceManager.GetString("Common_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export….
        /// </summary>
        public static string Common_Export {
            get {
                return ResourceManager.GetString("Common_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import….
        /// </summary>
        public static string Common_Import {
            get {
                return ResourceManager.GetString("Common_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import .sxcu….
        /// </summary>
        public static string Common_ImportSxcu {
            get {
                return ResourceManager.GetString("Common_ImportSxcu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Common_Open {
            get {
                return ResourceManager.GetString("Common_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string Common_OpenFolder {
            get {
                return ResourceManager.GetString("Common_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Common_Paste {
            get {
                return ResourceManager.GetString("Common_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Common_Remove {
            get {
                return ResourceManager.GetString("Common_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Common_Reset {
            get {
                return ResourceManager.GetString("Common_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all.
        /// </summary>
        public static string Common_ResetAll {
            get {
                return ResourceManager.GetString("Common_ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to defaults.
        /// </summary>
        public static string Common_ResetToDefaults {
            get {
                return ResourceManager.GetString("Common_ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search….
        /// </summary>
        public static string Common_Search {
            get {
                return ResourceManager.GetString("Common_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Common_Settings {
            get {
                return ResourceManager.GetString("Common_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear binding.
        /// </summary>
        public static string HotkeyCapture_ClearBinding {
            get {
                return ResourceManager.GetString("HotkeyCapture_ClearBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default.
        /// </summary>
        public static string HotkeyCapture_ResetToDefault {
            get {
                return ResourceManager.GetString("HotkeyCapture_ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add custom workflow.
        /// </summary>
        public static string Hotkeys_AddCustomWorkflow {
            get {
                return ResourceManager.GetString("Hotkeys_AddCustomWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the hotkey list.
        /// </summary>
        public static string Hotkeys_BackToList {
            get {
                return ResourceManager.GetString("Hotkeys_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the workflow name to open its step list. Click the hotkey chip to set / change / clear the key combo..
        /// </summary>
        public static string Hotkeys_Blurb {
            get {
                return ResourceManager.GetString("Hotkeys_Blurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone this workflow into a new editable copy.
        /// </summary>
        public static string Hotkeys_DuplicateTooltip {
            get {
                return ResourceManager.GetString("Hotkeys_DuplicateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey.
        /// </summary>
        public static string Hotkeys_Hotkey {
            get {
                return ResourceManager.GetString("Hotkeys_Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none yet — click + Add custom workflow below to create one).
        /// </summary>
        public static string Hotkeys_NoCustomYet {
            get {
                return ResourceManager.GetString("Hotkeys_NoCustomYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this workflow (built-ins can&apos;t be deleted).
        /// </summary>
        public static string Hotkeys_RemoveTooltip {
            get {
                return ResourceManager.GetString("Hotkeys_RemoveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore this built-in workflow&apos;s original steps and hotkey..
        /// </summary>
        public static string Hotkeys_ResetTooltip {
            get {
                return ResourceManager.GetString("Hotkeys_ResetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add actions with the picker below; drag the ⋮⋮ handle to reorder; toggle to mute without removing; × removes. Plumbing steps run automatically and aren&apos;t shown..
        /// </summary>
        public static string Hotkeys_StepEditorBlurb {
            get {
                return ResourceManager.GetString("Hotkeys_StepEditorBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow name.
        /// </summary>
        public static string Hotkeys_WorkflowName {
            get {
                return ResourceManager.GetString("Hotkeys_WorkflowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1-F10 fire global · 1-9,0 / arrows switch tab · QWERTY fires tab cell · Esc closes · right-click to edit.
        /// </summary>
        public static string Launcher_HelpHint {
            get {
                return ResourceManager.GetString("Launcher_HelpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Launcher_LabelIcon {
            get {
                return ResourceManager.GetString("Launcher_LabelIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Launcher_LabelLabel {
            get {
                return ResourceManager.GetString("Launcher_LabelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click to rename this tab — drop a file to switch tab without firing..
        /// </summary>
        public static string Launcher_TabRenameHint {
            get {
                return ResourceManager.GetString("Launcher_TabRenameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AresToys - Launcher.
        /// </summary>
        public static string Launcher_Title {
            get {
                return ResourceManager.GetString("Launcher_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle drag-and-drop mode — the launcher stays open and cells accept dropped files / folders / shortcuts..
        /// </summary>
        public static string Launcher_TooltipDragMode {
            get {
                return ResourceManager.GetString("Launcher_TooltipDragMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter cells by label or path. Empty cells and the F-row are unaffected; tabs without matches lose their title..
        /// </summary>
        public static string Launcher_TooltipSearch {
            get {
                return ResourceManager.GetString("Launcher_TooltipSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export every non-sensitive AresToys setting (theme, hotkeys, launcher cells, workflow steps, capture defaults, plugin selection) to a single JSON file you can sync between machines. Sensitive values (OAuth tokens, credentials) are not included — they&apos;d be unusable on another box anyway..
        /// </summary>
        public static string Settings_BackupHint {
            get {
                return ResourceManager.GetString("Settings_BackupHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup &amp; restore.
        /// </summary>
        public static string Settings_BackupTitle {
            get {
                return ResourceManager.GetString("Settings_BackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App-level preferences. Toggle behaviours that don&apos;t belong on a specific feature page..
        /// </summary>
        public static string Settings_Blurb {
            get {
                return ResourceManager.GetString("Settings_Blurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define preset chains of adjustments, filters and drawings (ShareX-compatible). Open the editor to add effects to a preset and preview the result on a sample image. Imports ShareX .sxie presets directly..
        /// </summary>
        public static string Settings_ImageEffectsHint {
            get {
                return ResourceManager.GetString("Settings_ImageEffectsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open image effects editor….
        /// </summary>
        public static string Settings_ImageEffectsOpen {
            get {
                return ResourceManager.GetString("Settings_ImageEffectsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image effects.
        /// </summary>
        public static string Settings_ImageEffectsTitle {
            get {
                return ResourceManager.GetString("Settings_ImageEffectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart not required — most surfaces switch immediately. A few labels (already-rendered tray submenus) refresh on next interaction..
        /// </summary>
        public static string Settings_LanguageHint {
            get {
                return ResourceManager.GetString("Settings_LanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart AresToys.
        /// </summary>
        public static string Settings_LanguageRestart {
            get {
                return ResourceManager.GetString("Settings_LanguageRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System default.
        /// </summary>
        public static string Settings_LanguageSystemDefault {
            get {
                return ResourceManager.GetString("Settings_LanguageSystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run AresToys when Windows starts.
        /// </summary>
        public static string Settings_StartWithWindows {
            get {
                return ResourceManager.GetString("Settings_StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds (or removes) AresToys to the per-user Windows startup list. No admin rights needed..
        /// </summary>
        public static string Settings_StartWithWindowsTooltip {
            get {
                return ResourceManager.GetString("Settings_StartWithWindowsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set AresToys as the default app for .sxie files.
        /// </summary>
        public static string Settings_SxieAssociation {
            get {
                return ResourceManager.GetString("Settings_SxieAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When on, double-clicking a .sxie file in Explorer opens the image-effects editor with the preset already imported — same flow as ShareX. Per-user only — doesn&apos;t touch system-wide settings or need admin rights..
        /// </summary>
        public static string Settings_SxieAssociationHint {
            get {
                return ResourceManager.GetString("Settings_SxieAssociationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick what each click on the tray icon should do. Right-click always opens the menu..
        /// </summary>
        public static string Settings_TrayClicksHint {
            get {
                return ResourceManager.GetString("Settings_TrayClicksHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon clicks.
        /// </summary>
        public static string Settings_TrayClicksTitle {
            get {
                return ResourceManager.GetString("Settings_TrayClicksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (do nothing).
        /// </summary>
        public static string Settings_TrayDoNothing {
            get {
                return ResourceManager.GetString("Settings_TrayDoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click.
        /// </summary>
        public static string Settings_TrayDoubleClick {
            get {
                return ResourceManager.GetString("Settings_TrayDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click.
        /// </summary>
        public static string Settings_TrayLeftClick {
            get {
                return ResourceManager.GetString("Settings_TrayLeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle click.
        /// </summary>
        public static string Settings_TrayMiddleClick {
            get {
                return ResourceManager.GetString("Settings_TrayMiddleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Sidebar_About {
            get {
                return ResourceManager.GetString("Sidebar_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string Sidebar_AppSettings {
            get {
                return ResourceManager.GetString("Sidebar_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Theme.
        /// </summary>
        public static string Sidebar_AppTheme {
            get {
                return ResourceManager.GetString("Sidebar_AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Settings.
        /// </summary>
        public static string Sidebar_CaptureSettings {
            get {
                return ResourceManager.GetString("Sidebar_CaptureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard Categories.
        /// </summary>
        public static string Sidebar_ClipboardCategories {
            get {
                return ResourceManager.GetString("Sidebar_ClipboardCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Console.
        /// </summary>
        public static string Sidebar_DebugConsole {
            get {
                return ResourceManager.GetString("Sidebar_DebugConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys &amp; Workflows.
        /// </summary>
        public static string Sidebar_HotkeysWorkflows {
            get {
                return ResourceManager.GetString("Sidebar_HotkeysWorkflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaders.
        /// </summary>
        public static string Sidebar_Uploaders {
            get {
                return ResourceManager.GetString("Sidebar_Uploaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Background Dark.
        /// </summary>
        public static string Theme_AccentBackgroundDark {
            get {
                return ResourceManager.GetString("Theme_AccentBackgroundDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Background Light.
        /// </summary>
        public static string Theme_AccentBackgroundLight {
            get {
                return ResourceManager.GetString("Theme_AccentBackgroundLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Danger.
        /// </summary>
        public static string Theme_AccentDanger {
            get {
                return ResourceManager.GetString("Theme_AccentDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two colors that flow everywhere AresToys uses an accent: primary buttons, toggle switches, the pinned-image border, drag-to-reorder indicators, and selected sidebar entries. Edit the hex values to see the changes apply live..
        /// </summary>
        public static string Theme_Blurb {
            get {
                return ResourceManager.GetString("Theme_Blurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Dark.
        /// </summary>
        public static string Theme_ForegroundDark {
            get {
                return ResourceManager.GetString("Theme_ForegroundDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Light.
        /// </summary>
        public static string Theme_ForegroundLight {
            get {
                return ResourceManager.GetString("Theme_ForegroundLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string Theme_PresetPicker {
            get {
                return ResourceManager.GetString("Theme_PresetPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface 1 (darkest).
        /// </summary>
        public static string Theme_Surface1 {
            get {
                return ResourceManager.GetString("Theme_Surface1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface 2 (medium).
        /// </summary>
        public static string Theme_Surface2 {
            get {
                return ResourceManager.GetString("Theme_Surface2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface 3 (lightest).
        /// </summary>
        public static string Theme_Surface3 {
            get {
                return ResourceManager.GetString("Theme_Surface3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface 1 → input fields and list rows. Surface 2 → main window body. Surface 3 → elevated panels and drag handles..
        /// </summary>
        public static string Theme_SurfacesHint {
            get {
                return ResourceManager.GetString("Theme_SurfacesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bard Rouge.
        /// </summary>
        public static string ThemePreset_BardRouge {
            get {
                return ResourceManager.GetString("ThemePreset_BardRouge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn My Eyes.
        /// </summary>
        public static string ThemePreset_BurnMyEyes {
            get {
                return ResourceManager.GetString("ThemePreset_BurnMyEyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleric Gold.
        /// </summary>
        public static string ThemePreset_ClericGold {
            get {
                return ResourceManager.GetString("ThemePreset_ClericGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom (current values).
        /// </summary>
        public static string ThemePreset_Custom {
            get {
                return ResourceManager.GetString("ThemePreset_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AresToys default.
        /// </summary>
        public static string ThemePreset_Default {
            get {
                return ResourceManager.GetString("ThemePreset_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid Green.
        /// </summary>
        public static string ThemePreset_DruidGreen {
            get {
                return ResourceManager.GetString("ThemePreset_DruidGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorcerer Purple.
        /// </summary>
        public static string ThemePreset_SorcererPurple {
            get {
                return ResourceManager.GetString("ThemePreset_SorcererPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warlock Red.
        /// </summary>
        public static string ThemePreset_WarlockRed {
            get {
                return ResourceManager.GetString("ThemePreset_WarlockRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard blue.
        /// </summary>
        public static string ThemePreset_WizardBlue {
            get {
                return ResourceManager.GetString("ThemePreset_WizardBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active window.
        /// </summary>
        public static string Tray_ActiveWindow {
            get {
                return ResourceManager.GetString("Tray_ActiveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App settings.
        /// </summary>
        public static string Tray_AppSettings {
            get {
                return ResourceManager.GetString("Tray_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        public static string Tray_AppTheme {
            get {
                return ResourceManager.GetString("Tray_AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string Tray_Capture {
            get {
                return ResourceManager.GetString("Tray_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture settings.
        /// </summary>
        public static string Tray_CaptureSettings {
            get {
                return ResourceManager.GetString("Tray_CaptureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color picker….
        /// </summary>
        public static string Tray_ColorPicker {
            get {
                return ResourceManager.GetString("Tray_ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color sampler.
        /// </summary>
        public static string Tray_ColorSampler {
            get {
                return ResourceManager.GetString("Tray_ColorSampler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string Tray_Fullscreen {
            get {
                return ResourceManager.GetString("Tray_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string Tray_Hotkeys {
            get {
                return ResourceManager.GetString("Tray_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last region.
        /// </summary>
        public static string Tray_LastRegion {
            get {
                return ResourceManager.GetString("Tray_LastRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string Tray_Monitor {
            get {
                return ResourceManager.GetString("Tray_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open clipboard.
        /// </summary>
        public static string Tray_OpenClipboard {
            get {
                return ResourceManager.GetString("Tray_OpenClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open launcher.
        /// </summary>
        public static string Tray_OpenLauncher {
            get {
                return ResourceManager.GetString("Tray_OpenLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open screenshot folder.
        /// </summary>
        public static string Tray_OpenScreenshotFolder {
            get {
                return ResourceManager.GetString("Tray_OpenScreenshotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to screen….
        /// </summary>
        public static string Tray_PinToScreen {
            get {
                return ResourceManager.GetString("Tray_PinToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR generator….
        /// </summary>
        public static string Tray_QrGenerator {
            get {
                return ResourceManager.GetString("Tray_QrGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Tray_Quit {
            get {
                return ResourceManager.GetString("Tray_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Tray_Region {
            get {
                return ResourceManager.GetString("Tray_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen recording.
        /// </summary>
        public static string Tray_ScreenRecording {
            get {
                return ResourceManager.GetString("Tray_ScreenRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen recording (GIF).
        /// </summary>
        public static string Tray_ScreenRecordingGif {
            get {
                return ResourceManager.GetString("Tray_ScreenRecordingGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle incognito.
        /// </summary>
        public static string Tray_ToggleIncognito {
            get {
                return ResourceManager.GetString("Tray_ToggleIncognito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tray_Tools {
            get {
                return ResourceManager.GetString("Tray_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Tray_Upload {
            get {
                return ResourceManager.GetString("Tray_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file….
        /// </summary>
        public static string Tray_UploadFile {
            get {
                return ResourceManager.GetString("Tray_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload from clipboard.
        /// </summary>
        public static string Tray_UploadFromClipboard {
            get {
                return ResourceManager.GetString("Tray_UploadFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webpage….
        /// </summary>
        public static string Tray_Webpage {
            get {
                return ResourceManager.GetString("Tray_Webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webpage… (install WebView2 Runtime).
        /// </summary>
        public static string Tray_WebpageInstallRuntime {
            get {
                return ResourceManager.GetString("Tray_WebpageInstallRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick which uploaders to use per content type. Multiple selections upload the same file to all of them; the resulting URLs end up on the clipboard, one per line..
        /// </summary>
        public static string Uploaders_Blurb {
            get {
                return ResourceManager.GetString("Uploaders_Blurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Uploaders_TabCustom {
            get {
                return ResourceManager.GetString("Uploaders_TabCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Uploaders_TabFile {
            get {
                return ResourceManager.GetString("Uploaders_TabFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Uploaders_TabImage {
            get {
                return ResourceManager.GetString("Uploaders_TabImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Uploaders_TabText {
            get {
                return ResourceManager.GetString("Uploaders_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Uploaders_TabUrl {
            get {
                return ResourceManager.GetString("Uploaders_TabUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Uploaders_TabVideo {
            get {
                return ResourceManager.GetString("Uploaders_TabVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active monitor capture.
        /// </summary>
        public static string Workflow_ActiveMonitorCapture {
            get {
                return ResourceManager.GetString("Workflow_ActiveMonitorCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active window capture.
        /// </summary>
        public static string Workflow_ActiveWindowCapture {
            get {
                return ResourceManager.GetString("Workflow_ActiveWindowCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color picker.
        /// </summary>
        public static string Workflow_ColorPicker {
            get {
                return ResourceManager.GetString("Workflow_ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color sampler.
        /// </summary>
        public static string Workflow_ColorSampler {
            get {
                return ResourceManager.GetString("Workflow_ColorSampler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual upload.
        /// </summary>
        public static string Workflow_ManualUpload {
            get {
                return ResourceManager.GetString("Workflow_ManualUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On clipboard.
        /// </summary>
        public static string Workflow_OnClipboard {
            get {
                return ResourceManager.GetString("Workflow_OnClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open launcher.
        /// </summary>
        public static string Workflow_OpenLauncher {
            get {
                return ResourceManager.GetString("Workflow_OpenLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open screenshot folder.
        /// </summary>
        public static string Workflow_OpenScreenshotFolder {
            get {
                return ResourceManager.GetString("Workflow_OpenScreenshotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        public static string Workflow_OpenSettings {
            get {
                return ResourceManager.GetString("Workflow_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR — read from screen region.
        /// </summary>
        public static string Workflow_QrReadFromRegion {
            get {
                return ResourceManager.GetString("Workflow_QrReadFromRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen recording (gif).
        /// </summary>
        public static string Workflow_RecordScreenGif {
            get {
                return ResourceManager.GetString("Workflow_RecordScreenGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen recording (mp4).
        /// </summary>
        public static string Workflow_RecordScreenMp4 {
            get {
                return ResourceManager.GetString("Workflow_RecordScreenMp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region capture.
        /// </summary>
        public static string Workflow_RegionCapture {
            get {
                return ResourceManager.GetString("Workflow_RegionCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save QR to history.
        /// </summary>
        public static string Workflow_SaveQrToHistory {
            get {
                return ResourceManager.GetString("Workflow_SaveQrToHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorten clipboard URL.
        /// </summary>
        public static string Workflow_ShortenClipboardUrl {
            get {
                return ResourceManager.GetString("Workflow_ShortenClipboardUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show clipboard popup.
        /// </summary>
        public static string Workflow_ShowPopup {
            get {
                return ResourceManager.GetString("Workflow_ShowPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle incognito.
        /// </summary>
        public static string Workflow_ToggleIncognito {
            get {
                return ResourceManager.GetString("Workflow_ToggleIncognito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload clipboard text.
        /// </summary>
        public static string Workflow_UploadClipboardText {
            get {
                return ResourceManager.GetString("Workflow_UploadClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload selected file.
        /// </summary>
        public static string Workflow_UploadSelectedFile {
            get {
                return ResourceManager.GetString("Workflow_UploadSelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webpage capture.
        /// </summary>
        public static string Workflow_WebpageCapture {
            get {
                return ResourceManager.GetString("Workflow_WebpageCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string WorkflowCategory_Capture {
            get {
                return ResourceManager.GetString("WorkflowCategory_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string WorkflowCategory_Clipboard {
            get {
                return ResourceManager.GetString("WorkflowCategory_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string WorkflowCategory_Other {
            get {
                return ResourceManager.GetString("WorkflowCategory_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string WorkflowCategory_Tools {
            get {
                return ResourceManager.GetString("WorkflowCategory_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string WorkflowCategory_Upload {
            get {
                return ResourceManager.GetString("WorkflowCategory_Upload", resourceCulture);
            }
        }
    }
}
