namespace AresToys.Core.Domain;

public enum ItemSource
{
    Clipboard,
    CaptureRegion,
    CaptureWindow,
    CaptureFullscreen,
    CaptureMonitor,
    CaptureWebpage,
    CaptureRecording,
    /// <summary>User-driven upload (file picker, "upload from clipboard", text editor).</summary>
    Manual,
    /// <summary>Generated by a workflow step (Add file / Add image / Add text / Convert text to QR …).
    /// Distinct from Manual because it carries no user-edit semantics — the workflow runtime is
    /// the agent of record.</summary>
    Pipeline,
}
